//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGOAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGOAL()
        {
            this.MASTERs = new HashSet<MASTER>();
            this.QoneGOALs = new HashSet<QoneGOAL>();
        }
    
        public int agoalID { get; set; }
        public Nullable<int> agoalValue { get; set; }
        public Nullable<int> subcategID { get; set; }
    
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER> MASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QoneGOAL> QoneGOALs { get; set; }
    }
}
