//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QoneGOAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QoneGOAL()
        {
            this.MASTERs = new HashSet<MASTER>();
            this.QtwoGOALs = new HashSet<QtwoGOAL>();
        }
    
        public int qonegoalID { get; set; }
        public Nullable<int> qonegoalValue { get; set; }
        public Nullable<int> agoalID { get; set; }
    
        public virtual AGOAL AGOAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER> MASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QtwoGOAL> QtwoGOALs { get; set; }
    }
}
