//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QthreeGOAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QthreeGOAL()
        {
            this.MASTERs = new HashSet<MASTER>();
            this.QfourGOALs = new HashSet<QfourGOAL>();
        }
    
        public int qthreegoalID { get; set; }
        public Nullable<int> qthreegoalValue { get; set; }
        public Nullable<int> qtwogoalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER> MASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QfourGOAL> QfourGOALs { get; set; }
        public virtual QtwoGOAL QtwoGOAL { get; set; }
    }
}
